# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efab839fc1462b02ac789e61651eb566bbde4980d0e511497ab4ab0ca40db567e7451de66d744cc152876738e8e910109ae70cada534dac968f107cd893f5e25

test:
  secret_key_base: 94d4e2fda1992efc340748de5fac09c34a88e74a796450c56951e39f2228eee782bf277770a45919920fcdde0cdb890e64db8fe82b87a4780bdc98b144c93de5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
